# Generated by Django 5.0 on 2023-12-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projectmanager_project_projectmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectmanager',
        ),
    ]
