# Generated by Django 5.0 on 2023-12-27 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_project_projectmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.projectmanager'),
        ),
    ]
